### ISSUE TITLE
Missing stripe customer?

### ISSUE THREAD

**Issue by awitherow** [gregives/poetry.tips#69]
https://github.com/gregives/poetry.tips/blob/3646ecfe35334555199c98c9590bba722b9955bc/app/api/stripe/route.ts#L62

**Comment by gregives** [comment]
Hi @awitherow, as far as I know, when a user purchases a product through Stripe Checkout, a _guest_ customer is created, instead of a normal Stripe customer: this is why I don't store it in Firebase. Have you noticed a bug related to this, or were you just wondering why I didn't store the Stripe customer in this case?

**Comment by gregives** [comment]
I'm going to close this but please do let me know if you've spotted anything wrong or need more info!
